Repository mental-health-org/mental-health-fe, pull requests merged in 2021-11, with the labels that each got.

#62 Feature/delete
  src/README.md
  src/components/Delete/Delete.tsx
  src/components/comment/Comment.tsx
  src/components/questionDetails/QuestionDetails.tsx
  src/containers/UserActionsBox/UserActionsBox.tsx
  src/containers/app/App.tsx
  src/containers/commentsContainer/CommentsContainer.tsx
  src/containers/viewQuestionPage/ViewQuestionPage.tsx
  src/images/HeLP_delete1.png
  src/styles/Delete.scss
  src/styles/UserActionsBox.scss
  src/utils/util.js
Labels: enhancement, feature

#64 Feature/edit
  src/components/Edit/Edit.tsx
  src/components/comment/Comment.tsx
  src/components/questionDetails/QuestionDetails.tsx
  src/containers/UserActionsBox/UserActionsBox.tsx
  src/containers/app/App.tsx
  src/images/HeLP_edit.png
  src/styles/Edit.scss
  src/styles/comment.scss
  src/styles/questionDetails.scss
  src/utils/util.js
Labels: enhancement, feature, UI/UX

#67 Fix/infinite loop question details view
  src/components/comment/Comment.tsx
  src/components/newComment/NewComment.tsx
  src/components/questionDetails/QuestionDetails.tsx
  src/containers/UserActionsBox/UserActionsBox.tsx
  src/containers/app/App.tsx
  src/containers/askPage/AskPage.tsx
  src/containers/commentsContainer/CommentsContainer.tsx
  src/containers/viewQuestionPage/ViewQuestionPage.tsx
Labels: bug, enhancement

#70 Feature/update landing page question cards styles
  src/components/questionCard/QuestionCard.tsx
  src/styles/Header.scss
  src/styles/questionCard.scss
Labels: UI/UX

#84 Feature/login with linked in
  package-lock.json
  package.json
  src/components/comment/Comment.tsx
  src/components/header/Header.tsx
  src/components/logoutButton/LogoutButton.tsx
  src/components/logoutButton/logoutButton.scss
  src/components/newQuestionForm/NewQuestionForm.tsx
  src/components/questionCard/QuestionCard.tsx
  src/components/questionDetails/QuestionDetails.tsx
  src/containers/UserActionsBox/UserActionsBox.tsx
  src/containers/app/App.tsx
  src/containers/askPage/AskPage.tsx
  src/containers/landingPage/LandingPage.tsx
  src/containers/login/Login.tsx
  src/containers/viewQuestionPage/ViewQuestionPage.tsx
  src/contexts/UserContext.tsx
  src/index.tsx
  src/styles/Header.scss
  src/styles/questionDetails.scss
  src/utils/util.js
Labels: feature
